import os
import click
from pyfiglet import Figlet
from remote import deploy_to_remote, run_on_remote, fetch_from_remote

__author__ = "d3roux"


@click.group()
def cli():
    """Map-Reduce tool to analyze cowrie log files on remote servers over time and create a visualization of the data.

    Uses multiple log files <cowrie.json.YYYY-MM-DD> to create a cummulated log file and a visualization.
    Log files can exist locally or being generated by cowrie on a remote droplet.

    LOCAL: python cli.py local --log-file-path  PATH

    REMOTE: python cli.py run-remote -i 123.456.789.10 -p 2112 -u root -pw pass
    """
    # f = Figlet(font='slant')
    # print(f.renderText('cowralyze'))
    pass


@click.command()
@click.option('--ip', '-i')
@click.option('--port', '-p')
@click.option('--user', '-u')
@click.option('--pw', '-pw')
def run_remote(ip, port, user, pw):
    deploy_to_remote(ip, port, user, pw)
    run_on_remote()
    fetch_from_remote(ip, port, user, pw)


@click.command()
def visualize():
    os.system("python visualize.py reduced.json")


cli.add_command(run_remote)
cli.add_command(visualize)

if __name__ == "__main__":
    # !/usr/bin/env python3
    cli()
